services:
  website:
    container_name: event_o_clock
    build:
      dockerfile: website.Dockerfile

    ports:
      - "3000:3000"
    env_file: .env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      dockerfile: database.Dockerfile

    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: eventuser
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: eventoclock
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  db_data:
